# Семинар 1: знакомство с NumPy


## Немного про Jupyter notebook

Полная документация: https://devpractice.ru/python-lesson-6-work-in-jupyter-notebook/

---
В Jupyter Notebook есть два режима работы: режим _команд_ и режим _редактирования_

_Командный_ режим нужен для того, чтобы взаимодействовать и управлять ячейками (добавлять, удалять, запускать, копировать, ...)

В режиме _редактирования_ вы меняете содержимое ячейки.

Ячейки бывают двух основных типов, _код_ и _разметка_

### Полезные команды

(находясь в командном режиме)

- `a` - добавить пустую ячейку сверху

- `b` - добавить пустую ячейку снизу
- `c` - скопировать текущую ячейку
- `v` - вставить скопированную ячейку
- `d` - удалить текущую ячейку
- `x` - вырезать (удалить и скопировать) текущую ячейку
- `m` - изменить тип выбранной ячейки на "разметка"
- `y` - изменить тип выбранной ячейки на "код"
- `z` - отменить последнее действие


- `Enter` - начать редактировать выбранную ячейку

(будучи в режим редактирования ячейки)
- `esc` - вернуться в командный режим

(будучи в любом режиме)

- `Ctrl + Enter` - запустить выбранную ячейку
- `Shift + Enter` - запустить выбранную ячейку и выбрать следующую

In [2]:
# ячейка с кодом, при выполнении которой появится output
2 + 2

4

*А это ячейка с неразмеченным текстом (markdown формат)*

In [3]:
# your code

[Здесь](https://athena.brynmawr.edu/jupyter/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb) находится <s>не</s>большая заметка о используемом языке разметки Markdown. Он позволяет:

0. Составлять упорядоченные списки
1. Выделять *текст* <s>при</s> **необходимости**
2. Добавлять [ссылки](http://imgs.xkcd.com/comics/the_universal_label.png)


* Составлять неупорядоченные списки

Делать вставки с помощью LaTex:
    
$
\left\{
\begin{array}{ll}
x = 16 \sin^3 (t) \\
y = 13 \cos (t) - 5 \cos (2t) - 2 \cos (3t) - \cos (4t) \\
t \in [0, 2 \pi]
\end{array}
\right.$

In [4]:
2 + 2

4

## Numpy

- документация: http://www.numpy.org/

### Python list vs numpy 1d array

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [5]:
# pip install numpy==[version]

In [6]:
import numpy as np

In [7]:
a = [x for x in range(10)]
a # list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Что изменится, если перевести обычный list в numpy array?

In [8]:
vec = np.array(a) # nupmy 1d array -> vector
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(vec)

numpy.ndarray

In [10]:
vec.shape # a.shape: 'list' object has no attribute 'shape'

(10,)

In [11]:
vec.ndim # одномерный массив

1

Что еще умеем?

In [12]:
vec > 0 # для python-массива получили бы ошибку 'TypeError': '>' not supported between instances of 'list' and 'int'

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Умножение:

In [13]:
# 1d numpy вектор
vec * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# python list
a * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Сложение:

In [15]:
print(vec)
vec + 10

[0 1 2 3 4 5 6 7 8 9]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
print(a)
a + 10 # TypeError: can only concatenate list (not "int") to list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


TypeError: can only concatenate list (not "int") to list

Такое поведение справедливо и для других привычных нам операций.  
Из векторов можно собирать матрицы...

### Матрицы в Numpy

In [17]:
mat = np.array([[1, 2], [3, 4], [5, 6]])
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
mat.shape # размер матрицы (строки x столбцы)

(3, 2)

In [19]:
mat.ndim # число осей

2

При этом тип объекта такой же:

In [20]:
type(mat)

numpy.ndarray

In [21]:
mat.dtype

dtype('int64')

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

<img src="https://i.sstatic.net/70IaS.gif" width="50%">

In [22]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
np.sum(mat) # просуммировали все значения в матрице

np.int64(21)

In [24]:
np.sum(mat, axis=0)

array([ 9, 12])

In [25]:
np.sum(mat, axis=1)

array([ 3,  7, 11])

Транспонируем матрицу:

In [26]:
mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [27]:
mat.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Размеры массивов можно менять:

In [28]:
mat # исходная матрица

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
mat.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
mat.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
mat.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

Индексирование:

In [32]:
mat # исходня матрица

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
mat[:, 1]

array([2, 4, 6])

In [34]:
mat[2, :]

array([5, 6])

In [35]:
mat[1:2, 0]

array([3])

In [36]:
mat[::2, :]

array([[1, 2],
       [5, 6]])

#### Арифметические операции:

In [37]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
mat + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [39]:
mat * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [40]:
mat**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [41]:
mat + mat**2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [42]:
mat * mat**2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [43]:
np.sin(mat)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [44]:
np.log(mat) # натуральный логарифм

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947]])

#### Матричное умножение:

<img src="https://madewithml.com/static/images/foundations/numpy/dot.gif">

https://madewithml.com/courses/foundations/numpy/

In [45]:
mat.dot((mat**2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [46]:
mat @ (mat**2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [47]:
# mat.dot(mat**2) # ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

#### Broadcasting

https://numpy.org/doc/stable/user/basics.broadcasting.html

Broadcasting — это механизм NumPy, который позволяет выполнять операции над массивами разных размеров, автоматически «растягивая» меньший массив до нужного shape без копирования данных

Зачем это нужно:
- Проще код: меньше ручного reshape и циклов.
- Быстрее: вычисления векторизованы, работают на уровне C.
- Практично в ML: нормализация признаков, вычисление расстояний, сдвиг/масштабирование батчей и т.д.

Пример:

```
X = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

b = np.array([10, 20, 30])  # shape (3,)

X + b
# b "растягивается" до (2, 3):
# [[11, 22, 33],
#  [14, 25, 36]]

```

In [48]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
mat + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [50]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [51]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
mat + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Булевы массивы:

In [53]:
is_even = mat % 2 == 0
print(is_even)

[[False  True]
 [False  True]
 [False  True]]


In [54]:
np.sum(is_even)

np.int64(3)

Булевы массивы позволяют вытаскивать элементы с True из массива того-же размера

In [55]:
mat[mat % 2 == 0]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [56]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [57]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [58]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [59]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
np.hstack((mat, np.zeros(mat.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.],
       [5., 6., 0., 0.]])

In [61]:
np.vstack((mat, np.zeros(mat.shape)))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Генерация случайных чисел:

In [62]:
np.__version__

'2.1.3'



> In NumPy, the recommended way to generate random numbers is to use the numpy.random.default_rng() function, which creates an instance of the Generator class. This modern approach offers better performance, statistical properties, and reproducibility compared to the legacy methods блок с цитатой



В последних версиях NumPy рекомендует использовать `np.random.default_rng(...)` и `Generator.integers(...)` вместо привычных многим `np.random.randint`. Старый RandomState‑API оставлен для совместимости, не удалён и не объявлен deprecated

[old version]

In [63]:
np.random.rand(2, 3)

array([[0.02432227, 0.96714653, 0.82134484],
       [0.7454489 , 0.64513489, 0.68577228]])

In [64]:
np.random.seed(42)
np.random.rand(2, 3)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [65]:
np.random.randn(3, 2)

array([[ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975]])

In [66]:
np.random.normal(2, 1, size=3)

array([2.24196227, 0.08671976, 0.27508217])

In [67]:
np.random.normal(2, 1, size=(3,2))

array([[1.43771247, 0.98716888],
       [2.31424733, 1.09197592],
       [0.5876963 , 3.46564877]])

In [68]:
?np.random.normal

In [69]:
np.random.randint(5, 10, size=3)

array([7, 8, 8])

[new version]

In [70]:
import numpy as np

rng = np.random.default_rng(2019)

rng.random((2, 3))

array([[0.14469964, 0.4422136 , 0.34029253],
       [0.96873942, 0.20012979, 0.43073434]])

In [71]:
rng.normal(size=(3, 2))

array([[-1.01436414, -0.33197281],
       [ 0.48662183, -0.33449225],
       [-0.06871662, -0.09096769]])

In [72]:
rng.normal(2, 1, size=3)

array([1.9180326 , 2.96572045, 2.29069319])

In [73]:
rng.integers(5, 10, size=3)

array([9, 9, 8])

Почему вообще используют `numpy`?

In [74]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [75]:
A

array([[0.59241457, 0.04645041, 0.60754485, ..., 0.73789692, 0.55435405,
        0.61172075],
       [0.41960006, 0.24773099, 0.35597268, ..., 0.36891364, 0.46253472,
        0.74747094],
       [0.0366832 , 0.25243694, 0.71334959, ..., 0.02246931, 0.26867736,
        0.54163421],
       ...,
       [0.50603128, 0.40844284, 0.94332246, ..., 0.08616583, 0.74243616,
        0.58857629],
       [0.44457922, 0.90872094, 0.14662732, ..., 0.1282828 , 0.05096895,
        0.9951872 ],
       [0.99979607, 0.19175757, 0.13379681, ..., 0.47278005, 0.33219026,
        0.88295176]])

In [76]:
B

array([[0.4685577 , 0.45504667, 0.03165676, ..., 0.48273307, 0.91675748,
        0.50071458],
       [0.1461412 , 0.54160755, 0.38759928, ..., 0.17762908, 0.78424354,
        0.44670452],
       [0.95173299, 0.61142057, 0.21762311, ..., 0.67910087, 0.32277441,
        0.26006383],
       ...,
       [0.84114573, 0.42377844, 0.49862821, ..., 0.86317526, 0.45447927,
        0.77601388],
       [0.76339014, 0.90365522, 0.5855405 , ..., 0.41155642, 0.53916522,
        0.59860742],
       [0.20144422, 0.75603267, 0.15411536, ..., 0.13107366, 0.73635657,
        0.25307068]])

In [ ]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

In [ ]:
%%time
C = A @ B

### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

In [ ]:
# your code here

2. Найти максимальный нечетный элемент в массиве.

In [ ]:
# your code here

3. Замените все нечетные элементы массива на ваше любимое число.

In [ ]:
# your code here

4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*

In [ ]:
# your code here

5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_

In [1]:
arr = np.array([int(i) for i in input('введите массив').split()])

NameError: name 'np' is not defined

6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_

In [ ]:
# your code here

7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
# your code here